### PR TITLE
Fixes bug so contrast "toStruct" routines search the correct model parameters

### PR DESCRIPTION
**Pull request by DrPaulSharp**
In the following scenarios, to model in the contrast should be:

For standard layers:
               One or more of the defined layers.

For custom layers/customXY:
               Only ONE defined custom file.

For standard layers with domains:
               TWO defined domain contrasts, with the model in the domains contrasts being one or more defined layers.

For custom layers/customXY with domains:
               Only ONE defined custom file. Domain contrasts should not be defined.

### CODE REVIEW

**Comment by arwelHughes** [comment]
Thaks Paul!
But........ as usual can someone help with the sequence of Git commands I need to look at this?
I'm in my fork on my 'newDomainsCalcs' branch, have just added and committed... so what do I do now without messing everything up?
Github suggests.....

$ gh pr checkout 155

.. but what branch etc should I be on to do that??
A

________________________________

**Comment by arwelHughes** [comment]
Hey Paul,
It's better, but now (with standard layers domains) fails in parseClassToStructs here.....

if isa(inputProblemDef, 'domainsClass') && isa(inputProblemDef.domainContrasts, 'domainContrastsClass')
    problemDef.numberOfDomainContrasts = inputStruct.numberOfDomainContrasts;
​    problemDef.domainContrastCustomFiles = inputStruct.domainContrastCustomFile;  <---- ****
else
    problemDef.numberOfDomainContrasts = 0;
    problemDef.domainContrastCustomFiles = ones(1,0);
end
..because there is no field for custom files set....


Unrecognized field name "domainContrastCustomFile".

Error in parseClassToStructs (line 369)
    problemDef.domainContrastCustomFiles = inputStruct.domainContrastCustomFile;

Error in RAT (line 10)
[problemDef,problemDefCells,problemDefLimits,priors,controls] = parseClassToStructs(problemDefInput,controls);



I guess this needs to be set to an empty array somewhere in toStruct for Standard Layers?
(I'm reluctant to hack it together in case I break something!)
Cheers,
Arwel




________________________________

**Comment by DrPaulSharp** [comment]
Ok, this latest push should resolve that issue - the field has been removed, because of course there cannot be custom files for the domain contrasts by definition. The code is available in the same place, hopefully it works now.

**Comment by DrPaulSharp** [comment]
Ok, this latest push should resolve that issue - the field has been removed, because of course there cannot be custom files for the domain contrasts by definition. The code is available in the same place, hopefully it works now.

**Comment by DrPaulSharp** [comment]
Ok, this latest push should resolve that issue - the field has been removed, because of course there cannot be custom files for the domain contrasts by definition. The code is available in the same place, hopefully it works now.

Cheers,
Paul

Dr Paul Sharp
Senior Software Scientist
ISIS Neutron and Muon Source
STFC Rutherford Appleton Laboratory
Harwell, Oxford
OX11 0QX
***@***.***

**Comment by arwelHughes** [comment]
Thaks Paul - that gets through classToStructs now... I'll let you know if I find anything amiss downstream.
Cheers!
Arwel

________________________________

**Comment by arwelHughes** [comment]
Hey Paul,
Standard layers domains now works perfectly! 🙂 However, we seem to have broken custom layers domains in the process.....

It now fails here (line 229 in domainsClass......)

            outStruct = mergeStructs(mainStruct, ...
                                     domainContrastStruct, ...
                                     domainRatioStruct);


.... and fails like this..

Unrecognized function or variable 'domainContrastStruct'.

Error in domainsClass/toStruct (line 230)
                                     domainContrastStruct, ...

Error in parseClassToStructs (line 90)
inputStruct = inputProblemDef.toStruct();

Error in RAT (line 10)
[problemDef,problemDefCells,problemDefLimits,priors,controls] = parseClassToStructs(problemDefInput,controls);

>>

Cheers,
Arwel

________________________________

**Comment by DrPaulSharp** [comment]
Ok, pushed another update. Let's try again . . .

**Comment by DrPaulSharp** [comment]
Ok, pushed another update. Let's try again . . .

Cheers,
Paul

Dr Paul Sharp
Senior Software Scientist
ISIS Neutron and Muon Source
STFC Rutherford Appleton Laboratory
Harwell, Oxford
OX11 0QX
***@***.***

**Comment by arwelHughes** [comment]
Yup, that did it - thanks Paul!

A

________________________________

**Pull request merged**
